services:
    php:
        build:
            context: ./.docker/php
        container_name: traffic_router_php
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=dev
            - XDEBUG_MODE=coverage

    nginx:
        image: nginx:alpine
        container_name: traffic_router_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

volumes:
    db_data:
